#pragma config(Sensor, in6,    LineRight,      sensorLineFollower)
#pragma config(Sensor, in7,    LineCenter,     sensorLineFollower)
#pragma config(Sensor, in8,    LineLeft,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl12, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port2,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions, line darkness, and surface lightness change from place to place,       *|
|*        so the value of 'threshold' may need to be changed to better suit your environment.         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/
void stopMotor()
{
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	wait1Msec(1000);

  int threshold = 2875;      /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */



  int drive = 1;
  int tala_1 = 40, tala_2 = 50;
  while(drive == 1)
  {
  	if(vexRT[Btn8U] == 1)
		{
			StopAllTasks();
			stopMotor();

		}


    // RIGHT sensor sees dark:
    if(SensorValue(LineRight) > threshold)
    {
      // counter-steer right:
      motor[leftMotor]  = 58;
      motor[rightMotor] = 29;
    }
    // CENTER sensor sees dark:
    if(SensorValue(LineCenter) > threshold)
    {
      // go straight
      motor[leftMotor]  = 58;
      motor[rightMotor] = 58;
    }
    // LEFT sensor sees dark:
    if(SensorValue(LineLeft) > threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 29;
      motor[rightMotor] = 58;
    }

    if(SensorValue(sonarSensor) > tala_1 && SensorValue(sonarSensor) < tala_2)
    {
    	stopMotor();
    	wait1Msec(1000);

    	motor[armMotor] = -127;
    	if (SensorValue(touchSensor) == 1)
    	{
    		motor[armMotor] = 0;
    		motor[clawMotor] = -127;
    		wait1Msec(1500);
    		tala_1 = 9998;
    		tala_2 = 9999;
    	}

    }
    if(SensorValue(sonarSensor) <= 10)
    {
    	stopMotor();
    	drive = 0;
    	break;
  	}
  }
  if(SensorValue(sonarSensor) <= 10)
  {
  		motor[clawMotor] = 127;
  		motor[armMotor] = 127;
  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
