#pragma config(Sensor, in6,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in7,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in8,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl12, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port2,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static const int threshold = 2875;
static const int LEFT = -1;
static const int RIGHT = 1;

int checkButtonSequence()
{
  if (vexRT[Btn7L] && vexRT[Btn7D])
        return 1;
  return 0;
}

int move(int speed) {

    motor[leftMotor] = speed;
    motor[rightMotor] = speed;

    return checkButtonSequence();
}

void wait(int milliseconds) {
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;

    wait1Msec(milliseconds);
}

void turn(int direction, int speed) {
    if (direction == LEFT) {
        motor[rightMotor] = speed;
        motor[leftMotor] = 0;
    }
    else {
        motor[rightMotor] = 0;
        motor[leftMotor] = speed;
    }
}

task main()
{
    while (1) {
        if (checkButtonSequence())
            break;
        if (SensorValue[rightLineFollower] > threshold) {
            turn(RIGHT, 70);
        }
        if (SensorValue[centerLineFollower] > threshold) {
            int exitcode = move(40);

            if (exitcode)
                break;
        }
        if (SensorValue[leftLineFollower] > threshold) {
            turn(LEFT, 70);
        }

    }
}
