#pragma config(Sensor, in6,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in7,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in8,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port2,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static const int threshold = 2875;

#include "verk6.c"


task main()
{

  motor[clawMotor] = 127;
  wait1Msec(500);


  clawReset();

  while (SensorValue[sonar] > 18)
    if (followLine(threshold))
      break;

  wait(1000);
  clawGrab();




  wait(1000);
  turnAround();

  while (SensorValue[sonar] > 17)
    if (followLine(threshold))
      break;

  wait(500);
  motor[clawMotor] = 60;
  wait1Msec(500);

}
