#pragma config(Sensor, in4,    LightSen,       sensorReflection)
#pragma config(Sensor, in6,    ,               sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorNone)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl12, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port2,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                   - VEX Smooth Sonar Tracking -                                    *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Ultrasonic sensor to detect objects, and maintain a desired distance from   *|
|*  that object.  However, with standart VEX motors, you may find it difficult to slowly creep up to  *|
|*  the object as the motors will not have enough power to move the robot.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.             *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Digital 5               sonarSensor         VEX Sonar Sensor    Front mounted, front facing     *|
|*    Motor - Port 2          leftMotor           VEX Motor           Left motor                      *|
|*    Motor - Port 3          rightMotor          VEX Motor           Right motor                     *|
\*-----------------------------------------------------------------------------------------------4246-*/

void stopMotor()
{
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(500);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
 	int run = 1;
 	while(run == 1)
	{
		while(SensorValue(LightSen) < 250)
		{
			int rundrive = 1;
			while(rundrive == 1)
			{


				while(SensorValue(sonarSensor) > 74 || SensorValue(sonarSensor) == -1)
				{
					motor[rightMotor] = 63;
					motor[leftMotor] = 63;

					if(vexRT[Btn8U] == 1)
					{
						StopAllTasks();
						stopMotor();
						rundrive = 0;
					}
					if(SensorValue(LightSen) >= 250)
					{
						stopMotor();
						rundrive = 0;
						break;
					}
				}
				while(SensorValue(sonarSensor) < 75)
				{
					motor[rightMotor] = -63;
					motor[leftMotor] = 63;
					if(SensorValue(LightSen) >= 250)
					{
						stopMotor();
						rundrive = 0;
						break;
					}
					if(SensorValue(sonarSensor) > 74 || SensorValue(sonarSensor) == -1)
					{
						break;
					}

					if(vexRT[Btn8U] == 1)
					{
						StopAllTasks();
						stopMotor();
						rundrive = 0;
					}
				}


			}
			if(SensorValue(LightSen) >= 250)
			{
				break;
			}
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
