#pragma config(Sensor, in1,    Pontetiometer,  sensorPotentiometer)
#pragma config(Sensor, in4,    LightSensor,    sensorReflection)
#pragma config(Sensor, in6,    LineFollow1,    sensorLineFollower)
#pragma config(Sensor, in7,    LineFollow2,    sensorLineFollower)
#pragma config(Sensor, in8,    LinEFollow3,    sensorLineFollower)
#pragma config(Sensor, dgtl1,  EncoderRight1,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderLeft1,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  TouchArm,       sensorTouch)
#pragma config(Sensor, dgtl8,  SonarIn,        sensorSONAR_cm)
#pragma config(Sensor, dgtl11, TouchButton,    sensorTouch)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           ClawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           ArmMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/

// Gylfi og Armann
// Rob2A3U vor2017
// Verkefni 2.1

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	int a; // Int value a
	int drivetime = 0; // Int value drivetime that is the time that motor goes in Msec
	int Msec = 1150; // Int value prefix for the time
	for (a = 0; a < 5; a = a +1) // For loop that goes 5 times
	{
		drivetime = drivetime + Msec; // drivetime value given a value then get + drivetime in after each loop
		wait1Msec(1000);						  // Robot waits for 1000 milliseconds before executing program

																	// Move forward at full power for 1150 msec
		motor[rightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
		motor[leftMotor]  = 127;		  // Motor on port3 is run at full (127) power forward
		wait1Msec(drivetime);

		motor[rightMotor] = 0;		    // Right motor giving the value to zero for 1 sec
		motor[leftMotor]  = 0;				// Left motor giving the value to zero for 1 sec
		wait1Msec(1000);

		motor[rightMotor] = -127;		  // Motor on port2 is run at full (127) power reverse
		motor[leftMotor]  = -127;		  // Motor on port3 is run at full (127) power reverse
		wait1Msec(drivetime);					// Robot waits until the drivetime runs out.

		motor[rightMotor] = 0;				// Right motor giving the value to zero for 1 sec
		motor[leftMotor]  = 0;				// Left motor giving the value to zero for 1 sec
		wait1Msec(1000);

	} // For loop ends
	// Program ends, and the robot stops
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
