#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	int fdtime = -488;
	int bdtime = 464;

	wait1Msec(1000);  // 1 Second Delay

	//Clear Encoders
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] > fdtime)  // While less than 5 rotations on the leftEncoder...
  	{
  			if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 60;
  			}
  			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 80;
  			}
  			else
  			{
  				motor[rightMotor] = 80;
  				motor[leftMotor] = 60;
  			}

  	}
	wait1Msec(1000);
 	motor[rightMotor] = 0;		    // Right motor giving the value to zero for 1 sec
 	motor[leftMotor]  = 0;
 	SensorValue[rightEncoder] = 0;
 	SensorValue[leftEncoder] = 0;

 	wait1Msec(1000);
 	motor[leftMotor] = -63;
 	motor[rightMotor] = 63;
 	SensorValue[rightEncoder] = 0;
 	SensorValue[leftEncoder] = 0;
 	wait1Msec(1000);

 	while(SensorValue[leftEncoder] > fdtime)  // While less than 5 rotations on the leftEncoder...
  	{
  			if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 60;
  			}
  			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 80;
  			}
  			else
  			{
  				motor[rightMotor] = 80;
  				motor[leftMotor] = 60;
  			}

  	}

  	wait1Msec(1000);
 	motor[rightMotor] = 0;		    // Right motor giving the value to zero for 1 sec
 	motor[leftMotor]  = 0;
 	SensorValue[rightEncoder] = 0;
 	SensorValue[leftEncoder] = 0;

 	motor[leftMotor] = 63;
 	motor[rightMotor] = -63;
 	wait1Msec(1000);


 	while(SensorValue[leftEncoder] > fdtime)  // While less than 5 rotations on the leftEncoder...
  	{
  			if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 60;
  			}
  			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 80;
  			}
  			else
  			{
  				motor[rightMotor] = 80;
  				motor[leftMotor] = 60;
  			}


  	}
  wait1Msec(1000);
 	motor[rightMotor] = 0;		    // Right motor giving the value to zero for 1 sec
 	motor[leftMotor]  = 0;
 	SensorValue[rightEncoder] = 0;
 	SensorValue[leftEncoder] = 0;

 	wait1Msec(1000);
 	motor[leftMotor] = 63;
 	motor[rightMotor] = -63;
 	wait1Msec(1000);
 	SensorValue[rightEncoder] = 0;
 	SensorValue[leftEncoder] = 0;

 	while(SensorValue[leftEncoder] > fdtime)  // While less than 5 rotations on the leftEncoder...
  	{
  			if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 60;
  			}
  			else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
  			{
  				motor[rightMotor] = 60;
  				motor[leftMotor] = 80;
  			}
  			else
  			{
  				motor[rightMotor] = 80;
  				motor[leftMotor] = 60;
  			}

  	}

}


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
